#ifndef _INSTRUCTION_EXCEPTION_HANDLER_H_
#define _INSTRUCTION_EXCEPTION_HANDLER_H_

VOID
EFIAPI
ExceptionHandler(
  IN EFI_EXCEPTION_TYPE ExceptionType,
  IN EFI_SYSTEM_CONTEXT SystemContext
);

#endif
